//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saml2AuthGateway.Services.Saml2Net48
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://test.enabler.info/current/Saml2Net48/", ConfigurationName="Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap")]
    public interface Saml2ServiceSoap
    {
        
        // CODEGEN: Generating message contract since element name userNameEncrypted from namespace https://test.enabler.info/current/Saml2Net48/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://test.enabler.info/current/Saml2Net48/GetFormAuthTicketForSaml2User", ReplyAction="*")]
        Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserResponse GetFormAuthTicketForSaml2User(Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://test.enabler.info/current/Saml2Net48/GetFormAuthTicketForSaml2User", ReplyAction="*")]
        System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserResponse> GetFormAuthTicketForSaml2UserAsync(Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequest request);
        
        // CODEGEN: Generating message contract since element name TestServiceResult from namespace https://test.enabler.info/current/Saml2Net48/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://test.enabler.info/current/Saml2Net48/TestService", ReplyAction="*")]
        Saml2AuthGateway.Services.Saml2Net48.TestServiceResponse TestService(Saml2AuthGateway.Services.Saml2Net48.TestServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://test.enabler.info/current/Saml2Net48/TestService", ReplyAction="*")]
        System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.TestServiceResponse> TestServiceAsync(Saml2AuthGateway.Services.Saml2Net48.TestServiceRequest request);
        
        // CODEGEN: Generating message contract since element name GetIPAddressResult from namespace https://test.enabler.info/current/Saml2Net48/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://test.enabler.info/current/Saml2Net48/GetIPAddress", ReplyAction="*")]
        Saml2AuthGateway.Services.Saml2Net48.GetIPAddressResponse GetIPAddress(Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://test.enabler.info/current/Saml2Net48/GetIPAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.GetIPAddressResponse> GetIPAddressAsync(Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequest request);
        
        // CODEGEN: Generating message contract since element name encryptedUserName from namespace https://test.enabler.info/current/Saml2Net48/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://test.enabler.info/current/Saml2Net48/RegisterEncryptedUserToRedirect", ReplyAction="*")]
        Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectResponse RegisterEncryptedUserToRedirect(Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://test.enabler.info/current/Saml2Net48/RegisterEncryptedUserToRedirect", ReplyAction="*")]
        System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectResponse> RegisterEncryptedUserToRedirectAsync(Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFormAuthTicketForSaml2UserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFormAuthTicketForSaml2User", Namespace="https://test.enabler.info/current/Saml2Net48/", Order=0)]
        public Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequestBody Body;
        
        public GetFormAuthTicketForSaml2UserRequest()
        {
        }
        
        public GetFormAuthTicketForSaml2UserRequest(Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.enabler.info/current/Saml2Net48/")]
    public partial class GetFormAuthTicketForSaml2UserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNameEncrypted;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool invalidate;
        
        public GetFormAuthTicketForSaml2UserRequestBody()
        {
        }
        
        public GetFormAuthTicketForSaml2UserRequestBody(string userNameEncrypted, bool invalidate)
        {
            this.userNameEncrypted = userNameEncrypted;
            this.invalidate = invalidate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFormAuthTicketForSaml2UserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFormAuthTicketForSaml2UserResponse", Namespace="https://test.enabler.info/current/Saml2Net48/", Order=0)]
        public Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserResponseBody Body;
        
        public GetFormAuthTicketForSaml2UserResponse()
        {
        }
        
        public GetFormAuthTicketForSaml2UserResponse(Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.enabler.info/current/Saml2Net48/")]
    public partial class GetFormAuthTicketForSaml2UserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFormAuthTicketForSaml2UserResult;
        
        public GetFormAuthTicketForSaml2UserResponseBody()
        {
        }
        
        public GetFormAuthTicketForSaml2UserResponseBody(string GetFormAuthTicketForSaml2UserResult)
        {
            this.GetFormAuthTicketForSaml2UserResult = GetFormAuthTicketForSaml2UserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestServiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestService", Namespace="https://test.enabler.info/current/Saml2Net48/", Order=0)]
        public Saml2AuthGateway.Services.Saml2Net48.TestServiceRequestBody Body;
        
        public TestServiceRequest()
        {
        }
        
        public TestServiceRequest(Saml2AuthGateway.Services.Saml2Net48.TestServiceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestServiceRequestBody
    {
        
        public TestServiceRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestServiceResponse", Namespace="https://test.enabler.info/current/Saml2Net48/", Order=0)]
        public Saml2AuthGateway.Services.Saml2Net48.TestServiceResponseBody Body;
        
        public TestServiceResponse()
        {
        }
        
        public TestServiceResponse(Saml2AuthGateway.Services.Saml2Net48.TestServiceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.enabler.info/current/Saml2Net48/")]
    public partial class TestServiceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestServiceResult;
        
        public TestServiceResponseBody()
        {
        }
        
        public TestServiceResponseBody(string TestServiceResult)
        {
            this.TestServiceResult = TestServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIPAddressRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIPAddress", Namespace="https://test.enabler.info/current/Saml2Net48/", Order=0)]
        public Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequestBody Body;
        
        public GetIPAddressRequest()
        {
        }
        
        public GetIPAddressRequest(Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetIPAddressRequestBody
    {
        
        public GetIPAddressRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIPAddressResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIPAddressResponse", Namespace="https://test.enabler.info/current/Saml2Net48/", Order=0)]
        public Saml2AuthGateway.Services.Saml2Net48.GetIPAddressResponseBody Body;
        
        public GetIPAddressResponse()
        {
        }
        
        public GetIPAddressResponse(Saml2AuthGateway.Services.Saml2Net48.GetIPAddressResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.enabler.info/current/Saml2Net48/")]
    public partial class GetIPAddressResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetIPAddressResult;
        
        public GetIPAddressResponseBody()
        {
        }
        
        public GetIPAddressResponseBody(string GetIPAddressResult)
        {
            this.GetIPAddressResult = GetIPAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterEncryptedUserToRedirectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterEncryptedUserToRedirect", Namespace="https://test.enabler.info/current/Saml2Net48/", Order=0)]
        public Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequestBody Body;
        
        public RegisterEncryptedUserToRedirectRequest()
        {
        }
        
        public RegisterEncryptedUserToRedirectRequest(Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.enabler.info/current/Saml2Net48/")]
    public partial class RegisterEncryptedUserToRedirectRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string encryptedUserName;
        
        public RegisterEncryptedUserToRedirectRequestBody()
        {
        }
        
        public RegisterEncryptedUserToRedirectRequestBody(string encryptedUserName)
        {
            this.encryptedUserName = encryptedUserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterEncryptedUserToRedirectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterEncryptedUserToRedirectResponse", Namespace="https://test.enabler.info/current/Saml2Net48/", Order=0)]
        public Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectResponseBody Body;
        
        public RegisterEncryptedUserToRedirectResponse()
        {
        }
        
        public RegisterEncryptedUserToRedirectResponse(Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://test.enabler.info/current/Saml2Net48/")]
    public partial class RegisterEncryptedUserToRedirectResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegisterEncryptedUserToRedirectResult;
        
        public RegisterEncryptedUserToRedirectResponseBody()
        {
        }
        
        public RegisterEncryptedUserToRedirectResponseBody(bool RegisterEncryptedUserToRedirectResult)
        {
            this.RegisterEncryptedUserToRedirectResult = RegisterEncryptedUserToRedirectResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface Saml2ServiceSoapChannel : Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Saml2ServiceSoapClient : System.ServiceModel.ClientBase<Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap>, Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Saml2ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Saml2ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), Saml2ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Saml2ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Saml2ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Saml2ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Saml2ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Saml2ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserResponse Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap.GetFormAuthTicketForSaml2User(Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequest request)
        {
            return base.Channel.GetFormAuthTicketForSaml2User(request);
        }
        
        public string GetFormAuthTicketForSaml2User(string userNameEncrypted, bool invalidate)
        {
            Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequest inValue = new Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequest();
            inValue.Body = new Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequestBody();
            inValue.Body.userNameEncrypted = userNameEncrypted;
            inValue.Body.invalidate = invalidate;
            Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserResponse retVal = ((Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap)(this)).GetFormAuthTicketForSaml2User(inValue);
            return retVal.Body.GetFormAuthTicketForSaml2UserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserResponse> Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap.GetFormAuthTicketForSaml2UserAsync(Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequest request)
        {
            return base.Channel.GetFormAuthTicketForSaml2UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserResponse> GetFormAuthTicketForSaml2UserAsync(string userNameEncrypted, bool invalidate)
        {
            Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequest inValue = new Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequest();
            inValue.Body = new Saml2AuthGateway.Services.Saml2Net48.GetFormAuthTicketForSaml2UserRequestBody();
            inValue.Body.userNameEncrypted = userNameEncrypted;
            inValue.Body.invalidate = invalidate;
            return ((Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap)(this)).GetFormAuthTicketForSaml2UserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Saml2AuthGateway.Services.Saml2Net48.TestServiceResponse Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap.TestService(Saml2AuthGateway.Services.Saml2Net48.TestServiceRequest request)
        {
            return base.Channel.TestService(request);
        }
        
        public string TestService()
        {
            Saml2AuthGateway.Services.Saml2Net48.TestServiceRequest inValue = new Saml2AuthGateway.Services.Saml2Net48.TestServiceRequest();
            inValue.Body = new Saml2AuthGateway.Services.Saml2Net48.TestServiceRequestBody();
            Saml2AuthGateway.Services.Saml2Net48.TestServiceResponse retVal = ((Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap)(this)).TestService(inValue);
            return retVal.Body.TestServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.TestServiceResponse> Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap.TestServiceAsync(Saml2AuthGateway.Services.Saml2Net48.TestServiceRequest request)
        {
            return base.Channel.TestServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.TestServiceResponse> TestServiceAsync()
        {
            Saml2AuthGateway.Services.Saml2Net48.TestServiceRequest inValue = new Saml2AuthGateway.Services.Saml2Net48.TestServiceRequest();
            inValue.Body = new Saml2AuthGateway.Services.Saml2Net48.TestServiceRequestBody();
            return ((Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap)(this)).TestServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Saml2AuthGateway.Services.Saml2Net48.GetIPAddressResponse Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap.GetIPAddress(Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequest request)
        {
            return base.Channel.GetIPAddress(request);
        }
        
        public string GetIPAddress()
        {
            Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequest inValue = new Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequest();
            inValue.Body = new Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequestBody();
            Saml2AuthGateway.Services.Saml2Net48.GetIPAddressResponse retVal = ((Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap)(this)).GetIPAddress(inValue);
            return retVal.Body.GetIPAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.GetIPAddressResponse> Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap.GetIPAddressAsync(Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequest request)
        {
            return base.Channel.GetIPAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.GetIPAddressResponse> GetIPAddressAsync()
        {
            Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequest inValue = new Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequest();
            inValue.Body = new Saml2AuthGateway.Services.Saml2Net48.GetIPAddressRequestBody();
            return ((Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap)(this)).GetIPAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectResponse Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap.RegisterEncryptedUserToRedirect(Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequest request)
        {
            return base.Channel.RegisterEncryptedUserToRedirect(request);
        }
        
        public bool RegisterEncryptedUserToRedirect(string encryptedUserName)
        {
            Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequest inValue = new Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequest();
            inValue.Body = new Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequestBody();
            inValue.Body.encryptedUserName = encryptedUserName;
            Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectResponse retVal = ((Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap)(this)).RegisterEncryptedUserToRedirect(inValue);
            return retVal.Body.RegisterEncryptedUserToRedirectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectResponse> Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap.RegisterEncryptedUserToRedirectAsync(Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequest request)
        {
            return base.Channel.RegisterEncryptedUserToRedirectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectResponse> RegisterEncryptedUserToRedirectAsync(string encryptedUserName)
        {
            Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequest inValue = new Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequest();
            inValue.Body = new Saml2AuthGateway.Services.Saml2Net48.RegisterEncryptedUserToRedirectRequestBody();
            inValue.Body.encryptedUserName = encryptedUserName;
            return ((Saml2AuthGateway.Services.Saml2Net48.Saml2ServiceSoap)(this)).RegisterEncryptedUserToRedirectAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Saml2ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Saml2ServiceSoap11))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Saml2ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);                
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Saml2ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress(SettingsKeyReader.SamlSoapWebService);
                // return new System.ServiceModel.EndpointAddress("https://localhost/Saml2/Saml2Net48/Saml2Service.asmx");
            }            
            if ((endpointConfiguration == EndpointConfiguration.Saml2ServiceSoap11))
            {
                return new System.ServiceModel.EndpointAddress(SettingsKeyReader.SamlSoapWebServiceHttp);
                // return new System.ServiceModel.EndpointAddress("http://localhost/Saml2/Saml2Net48/Saml2Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Saml2ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress(SettingsKeyReader.SamlSoapWebService);
                // return new System.ServiceModel.EndpointAddress("https://localhost/Saml2/Saml2Net48/Saml2Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Saml2ServiceSoap,
            Saml2ServiceSoap11,
            Saml2ServiceSoap12
        }
    }
}
